version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 778404080221.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=778404080221.dkr.ecr.eu-central-1.amazonaws.com/ninosrepo
      - IMAGE_TAG=$(echo $VERSION.$CODEBUILD_BUILD_NUMBER)
  build:
    commands:
      - docker build -t ninosrepo:latest .
      - echo rename image
      - docker tag ninosrepo:latest 778404080221.dkr.ecr.us-east-1.amazonaws.com/ninosrepo:latest
      - docker push 778404080221.dkr.ecr.us-east-1.amazonaws.com/ninosrepo:latest
      - printf '[{"name":"ninosapp","imageUri":"%s"}]' $REPO_URI:latest > NinosPipeline-imagedefinitions.json
      - docker image ls
  post_build:
    commands:
      - echo finish
artifacts:
  files:
    - NinosPipeline-imagedefinitions.json
